version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/
      - ${PHP_INI-./config/hosts}:/etc/hosts
      - ${LOG_DIR-./logs/nginx}:/var/log/nginx/
      - ${VHOSTS_DIR-./config/vhosts}:/etc/nginx/conf.d/
    links:
        - webserver
  webserver:
    build: ./bin/webserver/
    container_name: webserver
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
    links:
      - mysql
    ports:
      - "9000:9000"
  mysql:
    build: ./bin/mysql
    container_name: '5.7-mysql'
    command: mysqld --sql_mode=""
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: tiger