version: "3"

services:
  webserver:
    build:
      context: ./bin/webserver
    container_name: 'ws-8-php'
    restart: 'always'
    ports:
      - "82:80"
      - "444:443"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./config/vhosts}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./logs/apache2}:/var/log/apache2
  mysql:
    build: ./bin/mysql
    container_name: 'ws-8-mysql'
    command: mysqld --sql_mode=""
    restart: 'always'
    ports:
      - "3311:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: jDdjNAytlN
